export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";
export const USER_SIGNIN_ERROR = "USER_SIGNIN_ERROR";
export const USER_SIGNOUT = "USER_SIGNOUT";
export const OWNER_SIGNUP = "OWNER_SIGNUP";
export const OWNER_SIGNUP_FAILURE = "OWNER_SIGNUP_FAILURE";
export const CUSTOMER_SIGNUP = "CUSTOMER_SIGNUP";
export const CUSTOMER_SIGNUP_FAILURE = "CUSTOMER_SIGNUP_FAILURE";
export const CUSTOMER_UPDATE_FAILURE = "CUSTOMER_UPDATE_FAILURE";
export const OWNER_UPDATE = "OWNER_UPDATE";
export const OWNER_UPDATE_FAILURE = "OWNER_UPDATE_FAILURE";

export const OWNER_NEW_ORDER = "OWNER_NEW_ORDER";
export const OWNER_NEW_ORDER_FAILURE = "OWNER_NEW_ORDER_FAILURE";

export const OWNER_DELIVERED_ORDER = "OWNER_DELIVERED_ORDER";
export const OWNER_DELIVERED_ORDER_FAILURE = "OWNER_DELIVERED_ORDER_FAILURE";

export const OWNER_CANCELLED_ORDER = "OWNER_CANCELLED_ORDER";
export const OWNER_CANCELLED_ORDER_FAILURE = "OWNER_CANCELLED_ORDER_FAILURE";

export const OWNER_ORDER_UPDATE = "OWNER_ORDER_UPDATE";
export const OWNER_ORDER_UPDATE_FAILURE = "OWNER_ORDER_UPDATE_FAILURE";

export const OWNER_MENU = "OWNER_MENU";
export const OWNER_MENU_FETCH_FAILURE = "OWNER_MENU_FETCH_FAILURE";

export const OWNER_MENU_UPDATE = "OWNER_MENU_UPDATE";
export const OWNER_MENU_UPDATE_FAILURE = "OWNER_MENU_UPDATE_FAILURE";

export const OWNER_MENU_ADD = "OWNER_MENU_ADD";
export const OWNER_MENU_ADD_FAILURE = "OWNER_MENU_ADD_FAILURE";

export const CUSTOMER_UPDATE = "CUSTOMER_UPDATE";

export const LOCATION_UPDATE = "LOCATION_UPDATE";

export const CUSTOMER_ORDERS = "CUSTOMER_ORDERS";
export const CUSTOMER_ORDERS_FAILURE = "CUSTOMER_ORDERS_FAILURE";

export const CUSTOMER_NEWORDER = "CUSTOMER_NEWORDER";
export const CUSTOMER_NEWORDER_FAILURE = "CUSTOMER_NEWORDER_FAILURE";

export const CUSTOMER_ORDER_UPDATE = "CUSTOMER_ORDER_UPDATE";
export const CUSTOMER_ORDER_UPDATE_FAILURE = "CUSTOMER_ORDER_UPDATE_FAILURE";

export const CUSTOMER_FAVORITES = "CUSTOMER_FAVORITES";
export const CUSTOMER_FAVORITES_FAILURE = "CUSTOMER_FAVORITES_FAILURE";

export const ALL_RESTAURANTS = "ALL_RESTAURANTS";
export const ALL_RESTAURANTS_FAILURE = "ALL_RESTAURANTS_FAILURE";

export const UPDATE_FAV = "UPDATE_FAV";
export const UPDATE_FAV_FAILURE = "UPDATE_FAV_FAILURE";

export const CUSTOMER_DETAILS = "CUSTOMER_DETAILS";
export const CUSTOMER_DETAILS_FETCH_FAILURE = "CUSTOMER_DETAILS_FETCH_FAILURE";

export const UPDATE_ORDER_PAGE_SIZE = "UPDATE_ORDER_PAGE_SIZE";
export const UPDATE_ORDER_PAGE_NUMBER = "UPDATE_ORDER_PAGE_NUMBER";

export const OWNER_PROFILE_DETAILS = "OWNER_PROFILE_DETAILS";
export const OWNER_PROFILE_DETAILS_FAILURE = "OWNER_PROFILE_DETAILS_FAILURE";

export const CART_ADD = "CART_ADD";
export const CART_EMPTY = "CART_EMPTY";
export const CART_ITEM_UPDATE = "CART_ITEM_UPDATE";
export const CART_ITEM_DELETE = "CART_ITEM_DELETE";

export const OWNER_PROFILE_UPLOAD = "OWNER_PROFILE_UPLOAD";
export const CUSTOMER_PROFILE_UPLOAD = "CUSTOMER_PROFILE_UPLOAD";
export const CUSTOMER_PROFILE_UPLOAD_FAILURE =
  "CUSTOMER_PROFILE_UPLOAD_FAILURE";
export const OWNER_PROFILE_UPLOAD_FAILURE = "OWNER_PROFILE_UPLOAD_FAILURE";
export const DISH_IMAGE_UPLOAD = "DISH_IMAGE_UPLOAD";
export const DISH_IMAGE_UPLOAD_FAILURE = "DISH_IMAGE_UPLOAD_FAILURE";
